force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mail__c/fields/Tracking__c.field-meta.xml
<CustomField>
    <fullName>Tracking__c</fullName>
    <description>Generated code to allow a package to be tracked.</description>
    <label>Tracking Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeliveryController.cls
public class DeliveryController {
     public List<Mail__c> deliveredMail;
    public deliveryController(){
        this.deliveredMail= [SELECT Name, Delivery_Status__c, Address__c, Tracking__c, Claim_Paid_Out__c, Missing__c
                 			FROM Mail__c WHERE Delivery_Status__c = 'Delivered' LIMIT 150];    
       	
    }  
     public List<Mail__c> getDeliveredMail(){
        
        return deliveredMail;
        
    }
    

}